version: '3.2'
services:
  eureka-server:
    image: eureka-server
    ports:
     - "8001:8001"
  config-server:
    image: config-server
    depends_on:
     - eureka-server
    deploy:
      mode: replicated
      replicas: 1
  service:
    image: service
    depends_on:
     - eureka-server
     - config-server
     - hystrix-dashboard
     - zuul-proxy
    ports:
     - "8004:8004"
    deploy:
      mode: replicated
      replicas: 1
  client:
    image: client
    depends_on:
     - eureka-server
     - config-server
     - hystrix-dashboard
     - service
     - zuul-proxy
    ports:
     - "8005:8005"
    deploy:
      mode: replicated
      replicas: 1
  zuul-proxy:
    image: zuul-proxy
    depends_on:
     - eureka-server
    ports:
     - "8003:8003"
  config-server:
    image: config-server
    ports:
     - "8002:8002"
  hystrix-dashboard:
    image: hystrix-dashboard
    ports:
     - "8006:8006"
#  turbine:
#    image: turbine
#    ports:
#     - "8082:8082"

     
     
